### PR TITLE
added see-beauty

### LINKED ISSUE #3: HTML-CSS
- [x]   A new repo branch was created.
- [x]   HTML markup was developed.
- [x]  CSS styling was added.
- [x]  The GitHub pull request was reviewed by reviewers and the branch was merged to the master branch

### LINKED ISSUE #13: See Beauty
**A user can use a well-styled page**

STYLES 

- [x] Create a style for the background

### PR DESCRIPTION
**Pull request by gelilaa**
closes #13 and #3

### CODE REVIEW

**Review by IrynaSpyrydonova — COMMENTED** [review]
well done, @gelilaa , nicely done 👍🙂
I just have a small question. In the `overlay` you are using  variable `--secondary-color`, but unfortunately I haven't seen, that you would declare it somewhere (in the root or body). Or I didn't get something? 🙂 Thank you

**Comment by gelilaa** [comment]
oh yeah, I forgot to remove them they were attached with a bootstrap file.  i will clean them up now.

**Review by IrynaSpyrydonova — APPROVED** [review]
🚀👍

**Review by fmkarakus — COMMENTED** [review]
Well done @gelilaa.
In the preview on my computer, I can barely see the second line of holes. I think it will better if we move them upwards.

**Comment by gelilaa** [comment]
they work perfect in mine. lets merge the branch and if there is an overlap, I will fix it .

**Review by fmkarakus — APPROVED** [review]
Ok!

**Review by HazemBittar — APPROVED** [review]

**Pull request merged**
